name: CI

on: [push, pull_request]

jobs:
  Checando-pruebas:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_PASSWORD: root
        ports:
          - 3306/tcp # Explicitly specify tcp
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent" # Add host to health check
          --health-interval=2s # Reduce interval for faster feedback
          --health-timeout=5s
          --health-retries=10 # Increase retries

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3 # Use the latest version

      - name: Set up Python
        uses: actions/setup-python@v4 # Use the latest version
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Wait for MySQL to be ready
        run: |
          timeout 60 bash -c 'until mysqladmin ping -h 127.0.0.1 --silent; do sleep 1; done' # Explicit wait with timeout
          mysql -h 127.0.0.1 -u root -proot -e 'CREATE DATABASE IF NOT EXISTS test_db;' #Create database if not exists

      - name: Run tests
        env:
          DATABASE_URL: mysql+pymysql://root:root@127.0.0.1/test_db
        run: pytest