name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requeriments.txt
        pip install pytest pytest-qt

    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h"127.0.0.1" --silent; do
          sleep 1
        done

    - name: Initialize database
      env:
        DB_USER: root
        DB_PASSWORD: root
        DB_HOST: 127.0.0.1
        DB_NAME: test_db
      run: |
        python init_db.py

    - name: Run tests
      env:
        DB_USER: root
        DB_PASSWORD: root
        DB_HOST: 127.0.0.1
        DB_NAME: test_db
      run: |
        xvfb-run -a pytest
        pytest